Xiaoshuaige
OkayYang/EasyGPT pull request #1
Opened 2024-10-12 11:27 UTC by S18RNGchampion

2024-10-12 11:36 UTC, S18RNGchampion commented
牛逼

2024-10-12 11:47 UTC, OkayYang requested changes

2024-10-12 11:47 UTC, OkayYang commented on README.md
> +## 使用示例
为什么要演示这些

2024-10-12 11:47 UTC, OkayYang commented on easygpt-ui/README.md
> +本项目基于 MIT 协议开源，详细信息请查看 LICENSE 文件。
这里是前端介绍，不是后端技术介绍

2024-10-12 11:58 UTC, S18RNGchampion commented on easygpt-ui/README.md
> +本项目基于 MIT 协议开源，详细信息请查看 LICENSE 文件。
okok

2024-10-12 12:12 UTC, OkayYang approved these changes

2024-10-12 12:13 UTC, OkayYang approved these changes

2024-10-13 09:06 UTC, OkayYang approved these changes

2024-10-13 09:12 UTC, merged